### ISSUE TITLE
Single-char variable name

### ISSUE THREAD

**Issue by retorquere** [dsifford/astrocite#7]
It looks like the parser doesn't understand string concatenation, as it errors out on

```
@string{j = {a space between this }}
@article{key,
    author  = "Author",
    title   = "Title",
    year    = 1990,
    journal = j # "and this"
}
```

with

```
/Users/emile/github/better-bibtex/node_modules/astrocite-bibtex/lib/grammar.js:309
        return new peg$SyntaxError(peg$SyntaxError.buildMessage(expected, found), expected, found, location);
               ^
SyntaxError: Expected "=" but "#" found.
    at peg$buildStructuredError (/Users/emile/github/better-bibtex/node_modules/astrocite-bibtex/lib/grammar.js:309:16)
    at Object.peg$parse [as parse] (/Users/emile/github/better-bibtex/node_modules/astrocite-bibtex/lib/grammar.js:2505:15)
    at Object.<anonymous> (/Users/emile/github/better-bibtex/tt.ts:41:11)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.m._compile (/Users/emile/github/better-bibtex/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/emile/github/better-bibtex/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
```

**Comment by retorquere** [comment]
tested with:

```
const AST = require('astrocite-bibtex').AST
AST.parse(input)
```

**Comment by retorquere** [comment]
It's the var length. Vars of length 1 are not recognized

**Comment by dsifford** [comment]
Good catch. It looks like this is just because for whatever reason the concatinated string is expected to be 2 or more chars. I'll look into fixing.

**Comment by dsifford** [comment]
Haha.. Good timing!
